### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by newbrain** [MR-DOS/Si5351-lib#2]
There is no license file, and no indication of licensing in the Readme file.

Though I'm inclined to think this is just an oversight, it makes this code unusable in either FOSS or proprietary projects.

See, for example [here](https://choosealicense.com/no-permission/).

Considering the size of the code, a liberal license (BSD/MIT) could be a reasonable choice.
Thanks in advance.

**Comment by MR-DOS** [comment]
Added GPLv3 license.
